# Generated by Django 6.0.4 on 2026-05-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="order_order",
        ),
        migrations.AlterModelTable(
            name="orderitem",
            table="order_orderitem",
        ),
    ]
